### ISSUE TITLE
Archive page breaks

### ISSUE THREAD

**Issue by tedmagaoay** [AvaLovelace1/mini-hugo-webcomic#2]
In the artist-three chapter, the 2nd page is dated Feb 8, 2024.

![Screenshot from 2024-02-11 18-31-03](https://github.com/AvaLovelace1/mini-hugo-webcomic/assets/33870216/8c4b6386-69e6-49b0-a314-d5482913b790)

If I add another page in artist -two chapter, and date it Feb 9, 2024, the archive page will break.

![Screenshot from 2024-02-11 18-40-00](https://github.com/AvaLovelace1/mini-hugo-webcomic/assets/33870216/805c7048-455a-4997-ad13-dfd9ccca8230)

Thanks for sharing your mini Hugo Webcomic theme.

**Comment by AvaLovelace1** [comment]
Hello! This is expected behaviour as pages are **placed in order of earliest to latest date, by default**.

If you would like to display pages in some other order, **place a `weight` field in the frontmatter of each comic page `.md` file**. For example, in `content/comic/artist-one/1.md`:

```md
+++
weight = 10
date = 2023-12-01T00:00:00
+++
```

Pages with higher weight will be displayed first. Negative weights are allowed. If a page lacks a weight field, it will be displayed before the pages that do have a weight field.

I hope this helps!

**Comment by tedmagaoay** [comment]
Thank you so much.
